'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5420
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.5420.
'
Namespace Mobile
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="wsGeneralSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class wsGeneral
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/General_Ws/wsGeneral.asmx"
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RunSqlDs", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RunSqlDs(ByVal sSql As String, ByVal TableName As String, ByVal ProviderType As ProviderTypes) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("RunSqlDs", New Object() {sSql, TableName, ProviderType})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginRunSqlDs(ByVal sSql As String, ByVal TableName As String, ByVal ProviderType As ProviderTypes, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RunSqlDs", New Object() {sSql, TableName, ProviderType}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndRunSqlDs(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RunSql", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RunSql(ByVal sSql As String, ByVal Scalar As Boolean, ByVal ProviderType As ProviderTypes) As Object
            Dim results() As Object = Me.Invoke("RunSql", New Object() {sSql, Scalar, ProviderType})
            Return CType(results(0),Object)
        End Function
        
        '''<remarks/>
        Public Function BeginRunSql(ByVal sSql As String, ByVal Scalar As Boolean, ByVal ProviderType As ProviderTypes, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RunSql", New Object() {sSql, Scalar, ProviderType}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndRunSql(ByVal asyncResult As System.IAsyncResult) As Object
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Object)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RunSqlSp", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RunSqlSp(ByVal sSql As String, ByVal ProviderType As ProviderTypes) As Object
            Dim results() As Object = Me.Invoke("RunSqlSp", New Object() {sSql, ProviderType})
            Return CType(results(0),Object)
        End Function
        
        '''<remarks/>
        Public Function BeginRunSqlSp(ByVal sSql As String, ByVal ProviderType As ProviderTypes, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RunSqlSp", New Object() {sSql, ProviderType}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndRunSqlSp(ByVal asyncResult As System.IAsyncResult) As Object
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Object)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RunSql2", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RunSql2(ByVal sSql As String, ByVal Scalar As Boolean, ByVal ProviderType As ProviderTypes) As Boolean
            Dim results() As Object = Me.Invoke("RunSql2", New Object() {sSql, Scalar, ProviderType})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginRunSql2(ByVal sSql As String, ByVal Scalar As Boolean, ByVal ProviderType As ProviderTypes, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RunSql2", New Object() {sSql, Scalar, ProviderType}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndRunSql2(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum ProviderTypes
        
        '''<remarks/>
        SqlClient
        
        '''<remarks/>
        OleDb
        
        '''<remarks/>
        Odbc
        
        '''<remarks/>
        OracleClient
    End Enum
End Namespace
